# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(help_text='Type of equipment, make, model, etc.', max_length=200)),
                ('description', models.TextField(help_text='A brief description of equipment.', max_length=1000)),
                ('location', models.CharField(help_text='Lab/university address', max_length=200)),
                ('email', models.EmailField(help_text='Email address', max_length=100)),
            ],
        ),
    ]
