# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_device_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-creation_date']},
        ),
    ]
